set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN G11 [get_ports clk_25mhz]
set_property PACKAGE_PIN P5 [get_ports {led[3]}]
set_property PACKAGE_PIN P4 [get_ports {led[2]}]
set_property PACKAGE_PIN N4 [get_ports {led[1]}]
set_property PACKAGE_PIN P3 [get_ports {led[0]}]
create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]

set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nl_nadv]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_noe]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwait]
set_property PACKAGE_PIN G4 [get_ports fmc_clk]
set_property PACKAGE_PIN B1 [get_ports fmc_nl_nadv]
set_property PACKAGE_PIN A4 [get_ports fmc_noe]
set_property PACKAGE_PIN D3 [get_ports fmc_nwait]

set_property PACKAGE_PIN F2 [get_ports {fmc_a_hi[2]}]
set_property PACKAGE_PIN G1 [get_ports {fmc_a_hi[1]}]
set_property PACKAGE_PIN E4 [get_ports {fmc_a_hi[0]}]
set_property PACKAGE_PIN A5 [get_ports {fmc_nbl[1]}]
set_property PACKAGE_PIN B2 [get_ports {fmc_nbl[0]}]
set_property PACKAGE_PIN M4 [get_ports {fmc_ad[9]}]
set_property PACKAGE_PIN P2 [get_ports {fmc_ad[4]}]
set_property PACKAGE_PIN M2 [get_ports {fmc_ad[6]}]
set_property PACKAGE_PIN M3 [get_ports {fmc_ad[7]}]
set_property PACKAGE_PIN L1 [get_ports {fmc_ad[11]}]
set_property PACKAGE_PIN M1 [get_ports {fmc_ad[8]}]
set_property PACKAGE_PIN J4 [get_ports {fmc_ad[5]}]
set_property PACKAGE_PIN H1 [get_ports {fmc_ad[10]}]
set_property PACKAGE_PIN H3 [get_ports {fmc_ad[13]}]
set_property PACKAGE_PIN F4 [get_ports {fmc_ad[15]}]
set_property PACKAGE_PIN D1 [get_ports {fmc_ad[3]}]
set_property PACKAGE_PIN F1 [get_ports {fmc_ad[0]}]
set_property PACKAGE_PIN D4 [get_ports {fmc_ad[1]}]
set_property PACKAGE_PIN B3 [get_ports {fmc_ad[2]}]
set_property PACKAGE_PIN L2 [get_ports {fmc_ad[12]}]
set_property PACKAGE_PIN F3 [get_ports {fmc_ad[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne1]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne3]
set_property PACKAGE_PIN D2 [get_ports fmc_ne1]
set_property PACKAGE_PIN E2 [get_ports fmc_ne3]

set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwe]
set_property PACKAGE_PIN A2 [get_ports fmc_nwe]

create_clock -period 8.000 -name fmc_clk -waveform {0.000 4.000} [get_ports fmc_clk]



set_property DRIVE 8 [get_ports {fmc_ad[15]}]
set_property DRIVE 8 [get_ports {fmc_ad[14]}]
set_property DRIVE 8 [get_ports {fmc_ad[13]}]
set_property DRIVE 8 [get_ports {fmc_ad[12]}]
set_property DRIVE 8 [get_ports {fmc_ad[11]}]
set_property DRIVE 8 [get_ports {fmc_ad[10]}]
set_property DRIVE 8 [get_ports {fmc_ad[9]}]
set_property DRIVE 8 [get_ports {fmc_ad[8]}]
set_property DRIVE 8 [get_ports {fmc_ad[7]}]
set_property DRIVE 8 [get_ports {fmc_ad[6]}]
set_property DRIVE 8 [get_ports {fmc_ad[5]}]
set_property DRIVE 8 [get_ports {fmc_ad[4]}]
set_property DRIVE 8 [get_ports {fmc_ad[3]}]
set_property DRIVE 8 [get_ports {fmc_ad[2]}]
set_property DRIVE 8 [get_ports {fmc_ad[1]}]
set_property DRIVE 8 [get_ports {fmc_ad[0]}]
set_property SLEW FAST [get_ports {fmc_ad[15]}]
set_property SLEW FAST [get_ports {fmc_ad[14]}]
set_property SLEW FAST [get_ports {fmc_ad[13]}]
set_property SLEW FAST [get_ports {fmc_ad[12]}]
set_property SLEW FAST [get_ports {fmc_ad[11]}]
set_property SLEW FAST [get_ports {fmc_ad[10]}]
set_property SLEW FAST [get_ports {fmc_ad[9]}]
set_property SLEW FAST [get_ports {fmc_ad[8]}]
set_property SLEW FAST [get_ports {fmc_ad[7]}]
set_property SLEW FAST [get_ports {fmc_ad[6]}]
set_property SLEW FAST [get_ports {fmc_ad[5]}]
set_property SLEW FAST [get_ports {fmc_ad[4]}]
set_property SLEW FAST [get_ports {fmc_ad[3]}]
set_property SLEW FAST [get_ports {fmc_ad[2]}]
set_property SLEW FAST [get_ports {fmc_ad[1]}]
set_property SLEW FAST [get_ports {fmc_ad[0]}]
set_property DRIVE 8 [get_ports fmc_nwait]
set_property SLEW FAST [get_ports fmc_nwait]

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN C14 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN D13 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN D14 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN D12 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN A12 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN C12 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN A10 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rst_n]
set_property PACKAGE_PIN F14 [get_ports eth_mdc]
set_property PACKAGE_PIN F13 [get_ports eth_mdio]
set_property PACKAGE_PIN G14 [get_ports eth_rst_n]
create_clock -period 8.000 -name rgmii_rx_clk -waveform {0.000 4.000} [get_ports rgmii_rx_clk]
set_clock_groups -asynchronous -group [get_clocks rgmii_rx_clk] -group [get_clocks clk_125mhz_raw]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_raw] -group [get_clocks rgmii_rx_clk]
set_false_path -from [get_clocks fmc_clk] -to [get_clocks rgmii_rx_clk]

set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_en]
set_property PACKAGE_PIN H11 [get_ports rgmii_rx_clk]
set_property PACKAGE_PIN E13 [get_ports rgmii_rx_dv]
set_property PACKAGE_PIN A13 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN B14 [get_ports rgmii_tx_en]
set_property PACKAGE_PIN B13 [get_ports {rgmii_txd[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_gpio[0]}]
set_property PACKAGE_PIN N10 [get_ports {pmod_gpio[7]}]
set_property PACKAGE_PIN N11 [get_ports {pmod_gpio[6]}]
set_property PACKAGE_PIN P13 [get_ports {pmod_gpio[5]}]
set_property PACKAGE_PIN M14 [get_ports {pmod_gpio[4]}]

set_property PACKAGE_PIN P10 [get_ports {pmod_gpio[3]}]
set_property PACKAGE_PIN P11 [get_ports {pmod_gpio[2]}]
set_property PACKAGE_PIN P12 [get_ports {pmod_gpio[1]}]
set_property PACKAGE_PIN N14 [get_ports {pmod_gpio[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[0]}]
set_property PACKAGE_PIN C10 [get_ports {flash_dq[3]}]
set_property PACKAGE_PIN D10 [get_ports {flash_dq[2]}]
set_property PACKAGE_PIN B12 [get_ports {flash_dq[1]}]
set_property PACKAGE_PIN B11 [get_ports {flash_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports flash_cs_n]
set_property PACKAGE_PIN C11 [get_ports flash_cs_n]

set_clock_groups -asynchronous -group [get_clocks pclk_raw] -group [get_clocks clk_125mhz_raw]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_raw] -group [get_clocks pclk_raw]
set_clock_groups -asynchronous -group [get_clocks rgmii_rx_clk] -group [get_clocks pclk_raw]
set_clock_groups -asynchronous -group [get_clocks pclk_raw] -group [get_clocks rgmii_rx_clk]
set_clock_groups -asynchronous -group [get_clocks clk_25mhz] -group [get_clocks pclk_raw]


set_property DRIVE 8 [get_ports {flash_dq[3]}]
set_property DRIVE 8 [get_ports {flash_dq[2]}]
set_property DRIVE 8 [get_ports {flash_dq[1]}]
set_property DRIVE 8 [get_ports {flash_dq[0]}]
set_property DRIVE 8 [get_ports flash_cs_n]





