set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN G11 [get_ports clk_25mhz]
set_property PACKAGE_PIN P5 [get_ports {led[3]}]
set_property PACKAGE_PIN P4 [get_ports {led[2]}]
set_property PACKAGE_PIN N4 [get_ports {led[1]}]
set_property PACKAGE_PIN P3 [get_ports {led[0]}]
create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]
