set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN G11 [get_ports clk_25mhz]
set_property PACKAGE_PIN P5 [get_ports {led[3]}]
set_property PACKAGE_PIN P4 [get_ports {led[2]}]
set_property PACKAGE_PIN N4 [get_ports {led[1]}]
set_property PACKAGE_PIN P3 [get_ports {led[0]}]
create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]

set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nl_nadv]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_noe]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwait]
set_property PACKAGE_PIN G4 [get_ports fmc_clk]
set_property PACKAGE_PIN B1 [get_ports fmc_nl_nadv]
set_property PACKAGE_PIN A4 [get_ports fmc_noe]
set_property PACKAGE_PIN D3 [get_ports fmc_nwait]

set_property PACKAGE_PIN F2 [get_ports {fmc_a_hi[2]}]
set_property PACKAGE_PIN G1 [get_ports {fmc_a_hi[1]}]
set_property PACKAGE_PIN E4 [get_ports {fmc_a_hi[0]}]
set_property PACKAGE_PIN A5 [get_ports {fmc_nbl[1]}]
set_property PACKAGE_PIN B2 [get_ports {fmc_nbl[0]}]
set_property PACKAGE_PIN M4 [get_ports {fmc_ad[9]}]
set_property PACKAGE_PIN P2 [get_ports {fmc_ad[4]}]
set_property PACKAGE_PIN M2 [get_ports {fmc_ad[6]}]
set_property PACKAGE_PIN M3 [get_ports {fmc_ad[7]}]
set_property PACKAGE_PIN L1 [get_ports {fmc_ad[11]}]
set_property PACKAGE_PIN M1 [get_ports {fmc_ad[8]}]
set_property PACKAGE_PIN J4 [get_ports {fmc_ad[5]}]
set_property PACKAGE_PIN H1 [get_ports {fmc_ad[10]}]
set_property PACKAGE_PIN H3 [get_ports {fmc_ad[13]}]
set_property PACKAGE_PIN F4 [get_ports {fmc_ad[15]}]
set_property PACKAGE_PIN D1 [get_ports {fmc_ad[3]}]
set_property PACKAGE_PIN F1 [get_ports {fmc_ad[0]}]
set_property PACKAGE_PIN D4 [get_ports {fmc_ad[1]}]
set_property PACKAGE_PIN B3 [get_ports {fmc_ad[2]}]
set_property PACKAGE_PIN L2 [get_ports {fmc_ad[12]}]
set_property PACKAGE_PIN F3 [get_ports {fmc_ad[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne1]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne3]
set_property PACKAGE_PIN D2 [get_ports fmc_ne1]
set_property PACKAGE_PIN E2 [get_ports fmc_ne3]

set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwe]
set_property PACKAGE_PIN A2 [get_ports fmc_nwe]

connect_debug_port dbg_hub/clk [get_nets clk_100mhz]

create_clock -period 8.000 -name fmc_clk -waveform {0.000 4.000} [get_ports fmc_clk]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets fmc_clk_bufg]


set_property DRIVE 8 [get_ports {fmc_ad[15]}]
set_property DRIVE 8 [get_ports {fmc_ad[14]}]
set_property DRIVE 8 [get_ports {fmc_ad[13]}]
set_property DRIVE 8 [get_ports {fmc_ad[12]}]
set_property DRIVE 8 [get_ports {fmc_ad[11]}]
set_property DRIVE 8 [get_ports {fmc_ad[10]}]
set_property DRIVE 8 [get_ports {fmc_ad[9]}]
set_property DRIVE 8 [get_ports {fmc_ad[8]}]
set_property DRIVE 8 [get_ports {fmc_ad[7]}]
set_property DRIVE 8 [get_ports {fmc_ad[6]}]
set_property DRIVE 8 [get_ports {fmc_ad[5]}]
set_property DRIVE 8 [get_ports {fmc_ad[4]}]
set_property DRIVE 8 [get_ports {fmc_ad[3]}]
set_property DRIVE 8 [get_ports {fmc_ad[2]}]
set_property DRIVE 8 [get_ports {fmc_ad[1]}]
set_property DRIVE 8 [get_ports {fmc_ad[0]}]
set_property SLEW FAST [get_ports {fmc_ad[15]}]
set_property SLEW FAST [get_ports {fmc_ad[14]}]
set_property SLEW FAST [get_ports {fmc_ad[13]}]
set_property SLEW FAST [get_ports {fmc_ad[12]}]
set_property SLEW FAST [get_ports {fmc_ad[11]}]
set_property SLEW FAST [get_ports {fmc_ad[10]}]
set_property SLEW FAST [get_ports {fmc_ad[9]}]
set_property SLEW FAST [get_ports {fmc_ad[8]}]
set_property SLEW FAST [get_ports {fmc_ad[7]}]
set_property SLEW FAST [get_ports {fmc_ad[6]}]
set_property SLEW FAST [get_ports {fmc_ad[5]}]
set_property SLEW FAST [get_ports {fmc_ad[4]}]
set_property SLEW FAST [get_ports {fmc_ad[3]}]
set_property SLEW FAST [get_ports {fmc_ad[2]}]
set_property SLEW FAST [get_ports {fmc_ad[1]}]
set_property SLEW FAST [get_ports {fmc_ad[0]}]
set_property DRIVE 8 [get_ports fmc_nwait]
set_property SLEW FAST [get_ports fmc_nwait]
