set_max_delay -datapath_only -from [get_cells [list {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[7]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_a_ff_reg[8]} \
          mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[7]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_a_ff_reg[8]} \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_en/rx_a_ff_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_en/rx_a_ff_reg \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_a_ff_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/rx_a_ff_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/rx_a_ff_reg}]] -to [get_cells [list {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[7]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/reg_b_reg[8]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[7]} \
          {mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/reg_b_reg[8]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[0]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[10]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[11]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[12]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[13]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[14]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[15]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[16]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[17]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[18]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[19]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[1]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[20]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[21]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[22]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[23]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[24]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[25]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[26]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[27]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[28]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[29]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[2]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[30]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[31]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[32]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[3]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[4]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[5]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[6]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[7]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[8]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_ack/reg_b_reg[9]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[0]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[10]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[11]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[12]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[13]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[14]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[15]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[16]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[17]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[18]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[19]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[1]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[20]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[21]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[22]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[23]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[24]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[25]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[26]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[27]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[28]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[29]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[2]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[30]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[31]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[32]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[33]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[3]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[4]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[5]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[6]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[7]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[8]} \
          {sfp_quad_225/artix_bridge/bridge/sync_apb_completion/reg_b_reg[9]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/reg_b_reg[6]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[0]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[1]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[2]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[3]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[4]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[5]} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/reg_b_reg[6]}]] 5.000
set_max_delay -from [get_cells [list sfp_quad_225/artix_bridge/bridge/link_layer/sync_rx_to_tx_ll_link_up/dout0_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_ack/dout0_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_en/dout0_reg \
          sfp_quad_225/xg_mgmt/pcs/sync_sfp_los/dout0_reg \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_1/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_0/dout0_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_1/dout0_reg}]] -to [get_cells [list mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_en/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/link_layer/sync_rx_to_tx_ll_link_up/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_ack/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_ack/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_ack/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_en/dout1_reg \
          sfp_quad_225/xg_mgmt/pcs/sync_sfp_los/dout1_reg \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg}]] 5.000
set_max_delay -from [get_cells [list mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_ack/tx_a_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_en/tx_a_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_ack/tx_a_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_en/tx_a_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_ack/tx_a_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_en/tx_a_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_ack/tx_a_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_en/tx_a_reg \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/tx_a_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/tx_a_reg}]] -to [get_cells [list mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_rd_ptr/sync_en/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg \
          mgmt0_rx_cdc/cdc_fifo/sync_wr_ptr/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/link_layer/sync_rx_to_tx_ll_link_up/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_ack/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_ack/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_ack/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/sync_apb_completion/sync_en/sync/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_ack/dout1_reg \
          sfp_quad_225/artix_bridge/bridge/tx_cdc/sync_ctl/sync_tx_en/dout1_reg \
          sfp_quad_225/xg_mgmt/pcs/sync_sfp_los/dout1_reg \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[0].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[1].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[0].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[1].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[2].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_0/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].mac/sync_link_speed_1/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_rd_ptr/sync_en/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_ack/sync/dout1_reg} \
          {smpm_quad_224/lanes[2].macs/lanes[3].pcs/rx_fifo/sync_wr_ptr/sync_en/sync/dout1_reg}]] 5.000
########################################################################################################################
# Pin constraints

set_property PACKAGE_PIN C18 [get_ports clk_156m25_p]
set_property IOSTANDARD LVDS [get_ports clk_156m25_p]
set_property IOSTANDARD LVDS [get_ports clk_156m25_n]
set_property PACKAGE_PIN A24 [get_ports gpio_p]

set_property PACKAGE_PIN V7 [get_ports refclk_p]

set_property PACKAGE_PIN AF7 [get_ports smpm_0_tx_p]

set_property PACKAGE_PIN AE4 [get_ports smpm_1_rx_p]

set_property IOSTANDARD LVCMOS33 [get_ports {sfp0_rs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp0_rs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sfp0_tx_disable]
set_property PACKAGE_PIN P2 [get_ports sfp_0_rx_p]
set_property PACKAGE_PIN T2 [get_ports sfp_1_rx_p]
set_property PACKAGE_PIN C11 [get_ports sfp0_tx_disable]
set_property PACKAGE_PIN G14 [get_ports {sfp0_rs[1]}]
set_property PACKAGE_PIN G12 [get_ports {sfp0_rs[0]}]

set_property PACKAGE_PIN AD2 [get_ports smpm_2_rx_p]

########################################################################################################################
# Clocks

create_clock -period 6.400 -name clk_156m25_p -waveform {0.000 3.200} [get_ports clk_156m25_p]
create_clock -period 6.400 -name refclk_p -waveform {0.000 3.200} [get_ports refclk_p]

########################################################################################################################
# CDC constraints

# Synchronizer max delays: 5 ns (200 MHz) is << 1 cycle of both clocks
set_max_delay -datapath_only -from [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*a_ff*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*reg_b*" }] 5.000
set_max_delay -from [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*dout0_reg*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*dout1_reg*" }] 5.000
set_max_delay -from [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*tx_a_reg*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*dout1_reg*" }] 5.000

# APB clock domain crossings: 5 ns (200 MHz) is << 1 cycle of both clocks

########################################################################################################################
# Put the timestamp in the bitstream USERCODE

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]

########################################################################################################################
# Debugging


set_property IOSTANDARD LVCMOS33 [get_ports sfp0_rx_los]
set_property PACKAGE_PIN F14 [get_ports sfp0_rx_los]

set_clock_groups -asynchronous -group [get_clocks rxoutclk_raw] -group [get_clocks txoutclk_raw]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_156m25]
