create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN AB18 [get_ports {led[3]}]
set_property PACKAGE_PIN AB20 [get_ports {led[2]}]
set_property PACKAGE_PIN AB21 [get_ports {led[1]}]
set_property PACKAGE_PIN AB22 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN W19 [get_ports clk_25mhz]

set_property PACKAGE_PIN F6 [get_ports gtp_refclk_p]
set_property PACKAGE_PIN D9 [get_ports gtp_rx_p]

create_clock -period 6.400 -name gtp_refclk_p -waveform {0.000 3.200} [get_ports gtp_refclk_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gtp_rxusrclk2]
